export type VideoFile = {
  audio_bitrate: number;
  audio_codec: string;
  channel: number;
  container_type: string;
  display_x: number;
  display_y: number;
  duration: string;
  ff_video_profile: number;
  filesize: number;
  frame_bitrate: number;
  frame_rate_den: number;
  frame_rate_num: number;
  frequency: number;
  id: number;
  path: string;
  position: number;
  resolutionx: number;
  resolutiony: number;
  rotation: number;
  sharepath: string;
  video_bitrate: number;
  video_codec: string;
  video_level: number;
  video_profile: number;
  watched_ratio: number;
};
